<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Don, , t require OTP on this b_726c68</name>
   <tag></tag>
   <elementGuidId>abd4957f-edaf-4021-9aa0-21b9386d192f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-signin-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth-signin-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0316f8b8-f6db-4dc9-8306-92717ba7d4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-signin-button</value>
      <webElementGuid>cb69c3c2-9129-4fd1-9138-cf5b27442445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mfaSubmit</value>
      <webElementGuid>b0f78f43-167b-4684-8500-7bf7290bb199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>8960938b-5fa9-4d8c-879c-12f19951fcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>22482d2a-2061-4bd4-bbcb-24d4b2473a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>13620970-858a-4d14-aaad-6fd07a94004c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-signin-button&quot;)</value>
      <webElementGuid>acb1099e-2d81-43bb-80c3-40b11efea5f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth-signin-button']</value>
      <webElementGuid>e65de3b6-8040-4888-9f61-88234e7f550e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>25c20707-c788-4371-b480-62a3e9d8eeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>757510b1-77fe-4684-80d0-f09f9efa294f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'auth-signin-button' and @name = 'mfaSubmit' and @type = 'submit']</value>
      <webElementGuid>d8ceeb1d-c5d5-413f-b02a-c116a6fa36e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
