<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter OTP_otpCode</name>
   <tag></tag>
   <elementGuidId>f21ca8aa-1046-410e-bdb3-8cb7d247c855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-mfa-otpcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth-mfa-otpcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6152323b-20fe-4804-ad58-ec1e72e16833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>cc4c5e09-d59e-4af3-aefb-d5d85f929663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2e4d13d7-b15b-421d-a560-bfb4fce7e6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-mfa-otpcode</value>
      <webElementGuid>6cad325b-bbe2-4303-ad77-b9b9dddd1e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>68145943-392b-449a-9c9f-4fbc2377e55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otpCode</value>
      <webElementGuid>2f3eb02a-cf0c-4840-a93a-400fa146263d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 auth-autofocus auth-required-field</value>
      <webElementGuid>4bddadcc-f8b4-4b88-a90f-d39d8abd5e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-mfa-otpcode&quot;)</value>
      <webElementGuid>686a7ac2-a26a-40f6-b91c-1f9d08093a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth-mfa-otpcode']</value>
      <webElementGuid>9c6b0628-12f5-47b9-81ad-f87b5c299836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-mfa-form']/div/div/div/input</value>
      <webElementGuid>6101931d-b586-45e4-985d-83931a4fb41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>09d150df-d82e-467c-b0f8-fc6d760deb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'auth-mfa-otpcode' and @name = 'otpCode']</value>
      <webElementGuid>469a1cc5-bf54-4b30-bb0b-e0de2d421cea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
