<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot your password_password</name>
   <tag></tag>
   <elementGuidId>64b940bf-daae-43b7-aaed-1bb0ec15d367</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ap_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ap_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf97f2c4-3074-4b2f-af90-37c6837b98ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a2a41f24-dfd7-4e42-b7c4-1db1143794d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>77349c05-a63f-4b4c-88d1-ba8934305c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_password</value>
      <webElementGuid>1df96f22-34c7-403a-a4d2-1f67516b62a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c641e2fc-fa15-4f95-ad83-9b62ad5f950f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0b5854a1-f231-4bfe-a670-a37d14900429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 auth-autofocus auth-required-field</value>
      <webElementGuid>e9fa5ec3-a515-4d1d-8bd1-06f5a60b05be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_password&quot;)</value>
      <webElementGuid>1d11b2d9-c6cd-49c1-827c-f7bf80085b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ap_password']</value>
      <webElementGuid>61969cce-7ecf-4b24-aa82-10a3a6661c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>c1a7d6ee-ffc9-407a-80b5-6c942dd84b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>2d91bc2a-4f95-4fcf-a375-fd19ef72b225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'ap_password' and @name = 'password']</value>
      <webElementGuid>8c3272ed-91c9-472c-8546-432bf6d57555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
