<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Your List</name>
   <tag></tag>
   <elementGuidId>33726a93-0c91-4ceb-931d-93a09dfd4830</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='huc-view-your-list-button']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#huc-view-your-list-button > span.a-button-inner > a.a-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a4dccad-8d73-4e7d-8f8d-36e759ab7630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com/hz/wishlist/ls/1QG69H9OA4HTE?ref_=wl_dp_view_your_list</value>
      <webElementGuid>d436b4d2-87f3-4363-99bd-1d400f279d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>c5e2ec69-9f9b-4fd9-a5c5-190ef90b4594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Your List</value>
      <webElementGuid>10042c3b-abaf-448c-b5be-367e95482887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huc-view-your-list-button&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>b24d28fc-b1b8-4036-a2d5-a8e649554605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='huc-view-your-list-button']/span/a</value>
      <webElementGuid>9f2117a6-0b12-497f-9f2b-ef8beb7c6fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Your List')]</value>
      <webElementGuid>24a139d7-318e-437c-9628-98d834e22ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping List'])[1]/following::a[2]</value>
      <webElementGuid>30e2791f-b610-48f9-8b16-474930dd59f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to List'])[2]/following::a[3]</value>
      <webElementGuid>2f04a86c-b6d7-4e50-a69c-5a0366e3a3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspired by your list'])[1]/preceding::a[1]</value>
      <webElementGuid>4cadf878-f7b3-458d-96aa-e3f65d63b1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Basics Rectangular Gel Computer Mouse Pad | with Wrist Support Rest | Small | Black'])[1]/preceding::a[2]</value>
      <webElementGuid>8ace8b41-6477-4852-894b-7d0685c63c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Your List']/parent::*</value>
      <webElementGuid>89bdf846-880f-4872-a4ae-280cc46abe22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com/hz/wishlist/ls/1QG69H9OA4HTE?ref_=wl_dp_view_your_list')]</value>
      <webElementGuid>5dd6e876-0428-430d-b4f0-8c6eafdf7e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/span/a</value>
      <webElementGuid>f0b13a4d-7ed1-46e3-bc0c-0da523caa647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com/hz/wishlist/ls/1QG69H9OA4HTE?ref_=wl_dp_view_your_list' and (text() = 'View Your List' or . = 'View Your List')]</value>
      <webElementGuid>19e2567f-3f19-47e7-b821-2811ee240218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
